# Generated by Django 3.0.6 on 2020-05-27 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portalapp.Rotation'),
        ),
    ]
