# Generated by Django 3.0.6 on 2020-05-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0002_auto_20200527_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rotation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
